### ISSUE TITLE
Regarding execution of the code

### ISSUE THREAD

**Issue by purviprajapati196** [tomtung/parabel-rs#8]
![image](https://user-images.githubusercontent.com/38319034/64904833-4bdeda00-d6ed-11e9-846f-72de35702028.png)
![Capture](https://user-images.githubusercontent.com/38319034/64904842-687b1200-d6ed-11e9-9df8-e1bc298a4ebd.PNG)

How to get final precision of the Eurlex data?

**Comment by tomtung** [comment]
Precision is calculated and averaged over the entire data set. You can see here for an example https://github.com/tomtung/omikuji/blob/83f33e8c62694f0ec58d28d306a59246849701bb/src/model/eval.rs#L9

You can also use the binary executable directly instead of the Python wrapper for evaluation.

Let me know if you have more questions.

**Comment by purviprajapati196** [comment]
Dear Sir,

I have installed the cargo on ubuntu 18.04 and also run the training and
testing on the Eurlex dataset and got the result in the form of a text
file. So hereby attaching the screenshot of text file.

But sir, I would like to generate results in form of p@1,p@3,p@5....
How could i get it?
Kindly help me regarding this. I was stuck on this.

[image: r1 (1).JPG]

**Comment by purviprajapati196** [comment]
Respected Sir,

I would like to execute your code for different data set. Could you please
provide me some flow/video regarding the execution?

Kindly help me regarding this.

I am early waiting for your positive response.

Thanking you.
